### ISSUE TITLE
add a sample homepage layout and assets 

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo-Sample-Child-Theme#1]
to show how one would do that in a child theme

also, review the readme in homepages folder

**Comment by rnagle** [comment]
Added a skeleton JS file, placeholder LESS and CSS files used by the sample homepage layout.

The LESS files are set up in Gruntfile.js to compile to CSS when running `grunt less` or `grunt watch`.

I also update the general homepages readme to account for some changes I made recently to the Homepage class constructor.
