### ISSUE TITLE
Byline fuction no longer works

### ISSUE THREAD

**Issue by walinchus** [INN/Largo-Sample-Child-Theme#21]
On previous stories the name of the author would show up. Like in this screenshot:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/25959269/214633007-f0bafd2c-0c66-406d-9267-4c9c9039c0c9.png">

But now an additional box has popped up (top right): 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/25959269/214633302-969b669e-7b1a-4696-9f7c-fcb267af0177.png">
And there are only three options to add the author.

Here are the options: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25959269/214634016-5acfcca8-c656-4501-89d2-4e0bd7ac4806.png">

 The name in the byline box (Bottom right in the full spread up there.) Does not show up any more:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/25959269/214633647-3cffcdb6-0d37-49bd-859c-7b00f21a1172.png">

**Comment by benlk** [comment]
This should be reopened against https://github.com/WPBuddy/largo/

**Comment by walinchus** [comment]
This actually isn't a Largo issue, it's a Gutenberg issue. We switched to Gutenberg in 2018, but for some reason the byline function was still in the classic editor, go figure. Anyway, when the classic editor was finally deprecated this switched the bylines to the registered user format. For more, see here: https://kinsta.com/knowledgebase/how-to-change-author-in-wordpress/

**Comment by benlk** [comment]
You may also need to update your Co-Authors Plus install to cover the new version of Gutenberg.
